// get
export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

// add
export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST'
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS'
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE'

// update
export const UPDATE_ITEMS_REQUEST = 'UPDATE_ITEMS_REQUEST'
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS'
export const UPDATE_ITEMS_FAILURE = 'UPDATE_ITEMS_FAILURE'

// delete
export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST'
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS'
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE'

// pagination
export const PAGINATION_ITEMS_REQUEST = 'PAGINATION_ITEMS_REQUEST'
export const PAGINATION_ITEMS_SUCCESS = 'PAGINATION_ITEMS_SUCCESS'
export const PAGINATION_ITEMS_FAILURE = 'PAGINATION_ITEMS_FAILURE'

export const SEARCH_PAGI_ITEMS_REQUEST = 'SEARCH_PAGI_ITEMS_REQUEST'
export const SEARCH_PAGI_ITEMS_SUCCESS = 'SEARCH_PAGI_ITEMS_SUCCESS'
export const SEARCH_PAGI_ITEMS_FAILURE = 'SEARCH_PAGI_ITEMS_FAILURE'

export const LIMIT = 3